version: '3'

services:

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb-app
    restart: always
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  ethereum:
    build: ./server/api/samples/eth2/Docker/ganache-cli/
    container_name: ethereum-node-app
    restart: always
    volumes: 
      - ./data/ethereum:/data
    ports:
      - "8545:8545"
    entrypoint: ganache-cli -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
  
  ipfs:
    image: ipfs/go-ipfs:release
    container_name: ipfs-node-app
    restart: always
    volumes:
      - ./data/ipfs/staging:/export
      - ./data/ipfs/data:/data/ipfs
    ports:
      - "4001:4001" 
      - "5001:5001"
      - "8080:8080"
